parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     symfony
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            adha8y38hafhpaufyjadhsf89pGIUGIUG

parameters:
  easybacklog_api.api_key:          ******
  easybacklog_api.url:              https://easybacklog.com
  easybacklog_api.userid:           ***

  teams:
    raptor:
        name:   Raptor
        backlog:  1111
    prime:
        name:   Prime
        backlog:  2222
    ateam:
        name:   A-Team
        backlog:  3333
    gaia:
        name:   Gaia
        backlog:  4444