parameters:
    database_driver:   pdo_mysql
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     symfony
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            hgasdflhgsdhlfg7vt786sftstdv7t

    easybacklog_api.api_key:          z1mqsqagy9lvcrua9np5
    easybacklog_api.url:              https://easybacklog.com
    easybacklog_api.userid:           729

    teams:
        raptor:
            name:   Raptor
            backlog:  9862
        prime:
            name:   Prime
            backlog:  9555
        ateam:
            name:   A-Team
            backlog:  7869
        gaia:
            name:   Gaia
            backlog:  9248

    memcached.servers:
      - { host: 127.0.0.1, port: 11211 }
    #  - { host: 192.168.0.101, port: 11211 }  