application_default_homepage:
    pattern:  /
    defaults: { _controller: ApplicationDefaultBundle:Default:index }

application_default_homepage_data:
    pattern:  /data/{type}/{backlog}/{storyid}
    defaults: { _controller: ApplicationDefaultBundle:Default:data, type:general-deptstats, backlog:[9248,7869,9555,9862], storyid: 0 }

application_default_estimates:
    pattern:  /estimates
    defaults: { _controller: ApplicationDefaultBundle:Estimates:index }

application_default_team_name:
    pattern:  /estimates/team/{teamname}
    defaults: { _controller: ApplicationDefaultBundle:Estimates:team, teamname:gaia }

application_default_stories:
    pattern:  /stories
    defaults: { _controller: ApplicationDefaultBundle:Stories:index }

application_default_stories_team:
    pattern:  /stories/team/{teamname}
    defaults: { _controller: ApplicationDefaultBundle:Stories:team, teamname:gaia }    

application_default_stories_acceptancerate:
    pattern:  /stories/acceptancerate
    defaults: { _controller: ApplicationDefaultBundle:Stories:acceptancerate }

application_default_stories_acceptancerateteam:
    pattern:  /stories/acceptancerateteam/{teamname}
    defaults: { _controller: ApplicationDefaultBundle:Stories:acceptancerateteam, teamname:gaia }    

application_default_velocity:
    pattern:  /velocity
    defaults: { _controller: ApplicationDefaultBundle:Velocity:index }

application_default_velocity_team:
    pattern:  /velocity/team/{teamname}
    defaults: { _controller: ApplicationDefaultBundle:Velocity:team, teamname:gaia }