application_default_homepage:
    pattern:  /
    defaults: { _controller: ApplicationDefaultBundle:Default:index }
application_default_estimates:
    pattern:  /estimates
    defaults: { _controller: ApplicationDefaultBundle:Estimates:index }
application_default_estimates_data:
    pattern:  /estimates/data
    defaults: { _controller: ApplicationDefaultBundle:Estimates:data }    
